export const Roles = {
    ADMINISTRADOR: "ADMINISTRADOR",
    GERENCIA: "GERENTE",
}

export const Estados = {
    DISPONIBLE: "DISPONIBLE",
    OCUPADO: "OCUPADO",
    LIMPIEZA: "LIMPIEZA",
    MANTENIMIENTO: "MANTENIMIENTO",
    RESERVADO: "RESERVADO",
    CONFIRMADO: "CONFIRMADO",
    CANCELADO: "CANCELADO",
    PAGADO: "PAGADO",
    PENDIENTE: "PENDIENTE",
    VENCIDO: "VENCIDO",
}
